### ISSUE TITLE
Calling methods with . instead of :

### ISSUE THREAD

**Issue by SvenMarcus** [SvenMarcus/classy#2]
I've been thinking about a little change in the usage of classy. The way I implemented it would allow me to replace the `:` when calling methods with a simple `.`

So ```person.introduce()``` instead of ```person:introduce()```

However it would still be necessary to add the `self` argument when defining a method. 
For example: 
```
method = function(self, args)
end
```

There are a few arguments for and against this change:
Pros:
- function calling is the same as calling it from a simple table
- users don't have to know that there's a class being used behind the scenes
- most libraries and usually objects provided by C work with `.` , so in general more uniform way of calling functions

Cons:
- You still have to define the self argument. People could get confused when reading class source code and expect they need to use `:` when calling a method

I'd love to hear some thoughts on that!

**Comment by PhilipRoman** [comment]
I, personally, prefer the existing version. I think the colon notation is better and easier to understand for this case because it plays well with the "self" parameter. But I don't think this is such a big deal. I can certainly get used to either way!

**Comment by DarkWiiPlayer** [comment]
how about something like this?

```lua
local instance = -- this is our instance upvalue
function method_with_self(method) -- One closure per instance
  return function(...) -- One closure per method
    local old_self = self
    self = instance -- this is a global self
    method(...)
    self = old_self -- reset after done
  end
end
```

It removes the need for a `self` argument completely, "shadows" pre-existing `self` globals for the duration of the method call and allows accessing the instance that way. It may be a bit slower compared to arguments or upvalues, but the performance impact should be minimal for most use-cases, and optimizing interpreters like LuaJIT will usually reduce the number of table lookups.

The code could then look like this

```lua
class "Henry" {
  public {
    greet = function()
      print("Hello, I am "..self.name())
    end;
    name = function()
      return 'Henry'
    end;
  }
}
```

**Comment by SvenMarcus** [comment]
That seems like a good solution, I'll try it out and see how or if it affects performance

**Comment by SvenMarcus** [comment]
I've played around with it a little. Here's what I used: 
```
local function wrapperFunction(...)
                        local self_copy, changed
                        if not self or self ~= privateObj then
                            changed = true
                            self_copy = self
                            self = privateObj
                        end
                        local result = private_mt.func(...)
                        if changed then
                            self = self_copy
                        end
                        return result
                    end
```

I've used my little numerics script for benchmarking again. Pure metatable based implementation takes about 235 seconds to complete. The new implementation takes 347 seconds. 
I'm not sure if that's worth it, considering that the current implementation comes really close to the pure metatable approach.

**Comment by SvenMarcus** [comment]
I've pushed the changes to experimental_with_api_changes for review.
