### ISSUE TITLE
Virtual methods

### ISSUE THREAD

**Issue by dcanoh** [SvenMarcus/classy#6]
Please add virtual methods/fields for classes.

Thanks for your great work!

**Comment by SvenMarcus** [comment]
Methods can already be overridden in derived classes. If you're referring to pure virtual methods I do plan on implementing interfaces next

**Comment by SvenMarcus** [comment]
Interfaces are now implemented.
Note that abstract functions are currently only available in interfaces.

**Comment by dcanoh** [comment]
Thanks!
